### ISSUE TITLE
Address feedback from Tor UX team

### ISSUE THREAD

**Issue by hellais** [TheTorProject/ooni-wui#25]
@lindanlee gave some very useful feedback on the web UI that I am going to summarize here.

### web UI feedback

* [x] Put the text in a box so that the lines would be even. The uneven lines are disorienting.

* [x] Improvements to the Quiz prompt view

Comments:
I think that for a quiz like this, it would be better to not use T/F. It’s easier to read and easier to see what is being tested if there are text in the choices. I.e.: 
When my measurements are published, they contain: 
a) only anonymized information
b) potentially identifiable information 

* [x] Repetitive text when the answer is correct

* [x] Repetitive text when the answer is wrong

* [x] Shorten text in the Setup Sharing section

* [x] Ordering of the Setup Sharing options

* [x] The setup your tests section is inconsistent with the dashboard page

* [x] Get rid of information icon in the Setup your tests section

* [x] Better use of space below setup your tests section to indicate that a test is scheduled (migrated #26)

* [x] Fix bug in showing results for measurement (there should not be a tick when the row is red)

* [x] Do not use the work deck in the run tests page

Comments:
I don’t think that you need to use the word “deck” here, it’s a technical term that people have not seen before OONI; just saying “tor tests” seems fine to me. 

If you only have one test, I don’t think that there should be two buttons. Running it is the same as running the whole deck, and it’s confusing because it’s not a deck. I say that you just put a blue button that says “run this test” for test decks with single tests. 

* [x] Make the run button on the side

Comments:
I suggest that you make the run button a button to the side, similar to how it is in your mobile interface. That would make the interface more streamlined.  

* [x] Make the view box red

Comment:

If this isn't done why isn't this at the top of the table.

I think just putting the icons would be sufficient especially since the test decks are labelled at the top. This text clutters the table in a bad way.

Comment:

Why are some test results shown in a new window

Comment:

What is the log page for.
I don’t think we discussed this in the design. We should talk about what this page is for and what you plan to do with it. 

Here is the PDF with the comments:
[ooni-web-UI-lindas-feedback.pdf](https://github.com/TheTorProject/ooni-wui/files/739216/ooni-web-UI-lindas-feedback.pdf)

### Mobile browser

* [x] It’s especially critical to reduce this text for mobile interfaces. 

* [x] The Setup Sharing options are too crowded

* [x] The text in the Setup Sharing section is too big

* [x] The circle markers are too close to the action button

* [x] Improve presentation of test icons

* [x] Buttons are vertically arranged rather than all in the same row in the Dashboard

* [x] Table for the last 4 tests is too crowded

* [x] Footer should be in smaller font to appear all in one row

* [x] In the Measurements page the filter icons should be all on the same row

Here is the pdf with comments:

[ooni-web-ui-mobile-browser.pdf](https://github.com/TheTorProject/ooni-wui/files/739219/ooni-web-ui-mobile-browser.pdf)

**Comment by hellais** [comment]
I am going to answer some of the comments above:

>  Put the text in a box so that the lines would be even. The uneven lines are disorienting.

The text is actually already wrapped inside of a responsive column. I can potentially make it a bit thinner, but that would still lead to it appearing "uneven". I think the issue here is that each paragraph is fairly short so it doesn't reach the right point to wrap around enough to make it appear inside the box.
I think putting them inside a smaller "box" would make the text too long in the following views, so I am not sure this would be the best way.

> I think that for a quiz like this, it would be better to not use T/F. It’s easier to read and easier to see what is being tested if there are text in the choices. I.e.:
> When my measurements are published, they contain:
> a) only anonymized information
> b) potentially identifiable information

One of the reasons of changing the Quiz to be T/F as opposed to multiple choice was that this way it was going to be easier to answer it. This was discussed already in the UX review, I personally think this is a good choice, but you should probably ask @ebdet2002  what he thinks of this and if you both agree on this point then I can change it.

>  Ordering of the Setup Sharing options

The reason why the options are ordered in this way is that they are ordered based on what are the settings that a user is most likely interested in changing (or the ones we want to encourage them to change).
The number one thing that users are likely to change is how the upload results, that is why it's first, followed by if they should include their network name. All the other settings we actually don't really want them to change them and so they are placed last.

>  The setup your tests section is inconsistent with the dashboard page

This was also discussed quite a bit when doing the mockups. The rational behind this is that there is a difference between what is the first start and what is the UI when it's initialized. Since the two UIs cannot possibly be the same (the onboard cannot have the ability to run tests because ooniprobe is not yet configured at this point) we decided to pose more enphasis on the action that is most likely to be done by users here (toggle a test).
I think that in the end this works well and is not too disorienting since there is an iconography based queue that links what is in the onboard to what they see in the run tests page (the clock icon).

>  Get rid of information icon in the Setup your tests section

Since the deck description can potentially be fairly long I think on hover balloon is not adequate. Moreover having it viewed when you click on it I think makes it more confusing as we don't usually show modals expect when you click on a button. This would be inconsistent with, for example, filtering based on clicking on the icon in the past measurements page.

>  Make the view box red

I am against doing this as I think it makes the UI more visually noisy. Buttons that perform the same type of action should always be of the same color. I am OK with changing the color of a button **only** if that button performs an action of a different class. I would expect a red button to do something dangerous.

> Why are some test results shown in a new window

Some a shown in another page because they are multiple entry tests and what you are seeing is not actually the result, but just the listing of the results within that set of measurements.

**Comment by lindanlee** [comment]
> The text is actually already wrapped inside of a responsive column. I can potentially make it a bit thinner, but that would still lead to it appearing "uneven". I think the issue here is that each paragraph is fairly short so it doesn't reach the right point to wrap around enough to make it appear inside the box.
I think putting them inside a smaller "box" would make the text too long in the following views, so I am not sure this would be the best way.

Oh, I didn't know that it was already in a responsive column. I don't have a specific preference on the size of the column, and I agree that we can't make it appear too long. But I do think that we should, in some way, find a way to make the text wrap uniformly. Not starting a new line for new sentences would be one step. I noticed that there was one line on the first page (on my screenshots) that only had one word, but there was more text on the next line. 

> One of the reasons of changing the Quiz to be T/F as opposed to multiple choice was that this way it was going to be easier to answer it. This was discussed already in the UX review, I personally think this is a good choice, but you should probably ask @ebdet2002 what he thinks of this and if you both agree on this point then I can change it.

You are right, it is easier to answer it. Mine would more more difficult to answer, but would require the user to pay more attention to their answers. Think of the copy as a cue for your buttons in the interface--I'm trying to do the same with the quiz answers. Some people just click answers without reading the question, and the T/F would not inform them as well, but my scheme would at least make them acknowledge what they are answering. 

That being said, I respect your decision and am honestly fine with either. It is pretty good as is right now, and I may be micro-optimizing. 

> The reason why the options are ordered in this way is that they are ordered based on what are the settings that a user is most likely interested in changing (or the ones we want to encourage them to change).

This does make sense to me now--but this was not clearly communicated in any way to me. And as a new user, I don't think I would necessarily know that the first was the common thing to change. But then again, I haven't used OONI enough to say. I am now for this ordering. 

> This was also discussed quite a bit when doing the mockups. The rational behind this is that there is a difference between what is the first start and what is the UI when it's initialized. Since the two UIs cannot possibly be the same (the onboard cannot have the ability to run tests because ooniprobe is not yet configured at this point) we decided to pose more enphasis on the action that is most likely to be done by users here (toggle a test).
I think that in the end this works well and is not too disorienting since there is an iconography based queue that links what is in the onboard to what they see in the run tests page (the clock icon).

I see. It should be different to signal that they are doing different thing. Isabela and I thought it would not be immediately obvious as to what the toggle does and why they should toggle it, but we can't say for sure without asking the users. 

> Since the deck description can potentially be fairly long I think on hover balloon is not adequate. Moreover having it viewed when you click on it I think makes it more confusing as we don't usually show modals expect when you click on a button. This would be inconsistent with, for example, filtering based on clicking on the icon in the past measurements page.

Ah, I see. I would be for shortening the descriptions enough for them to fit into a balloon, and having a "read more" link to really thorough documentation. 

> I am against doing this as I think it makes the UI more visually noisy. Buttons that perform the same type of action should always be of the same color. I am OK with changing the color of a button only if that button performs an action of a different class. I would expect a red button to do something dangerous.

You're right. Red button does seem bad. But still, the colors look a little weird to me. Maybe we shouldn't make the whole row red? and have a column for detected anomalies/not and keep those red/green? I think that would look better. 

>Some a shown in another page because they are multiple entry tests and what you are seeing is not actually the result, but just the listing of the results within that set of measurements. 

Oh, I see. I think that this is confusing, though, and would ask that you consider consistent site behaviors, even if the results are not homogenous (and use text/styling to differentiate different tests).

**Comment by hellais** [comment]
> Oh, I didn't know that it was already in a responsive column. I don't have a specific preference on the size of the column, and I agree that we can't make it appear too long. But I do think that we should, in some way, find a way to make the text wrap uniformly. Not starting a new line for new sentences would be one step. I noticed that there was one line on the first page (on my screenshots) that only had one word, but there was more text on the next line.

We discussed this a bit with @ebdet2002 and came to the conclusion that the problem was that each sentence was placed inside of a new paragraph. Putting it all inside of the same paragraph makes it look a lot neater. We will go for this solution.

**Comment by hellais** [comment]
> Ah, I see. I would be for shortening the descriptions enough for them to fit into a balloon, and having a "read more" link to really thorough documentation.

I am going to take note of this as a possible future improvements, but am not going to implement this for the moment as it would require reworking how we manage deck specific documentation and possibly adding support for in-app contextual documentation (I don't like the idea of redirecting users to our website to consume crucial ooniprobe related documentation)

> You're right. Red button does seem bad. But still, the colors look a little weird to me. Maybe we shouldn't make the whole row red? and have a column for detected anomalies/not and keep those red/green? I think that would look better.

Yes, though this keying is used also consistently across desktop and mobile clients. I think we are going for the moment keep it as is and defer potential improvements to the results page to future work.

> Oh, I see. I think that this is confusing, though, and would ask that you consider consistent site behaviors, even if the results are not homogenous (and use text/styling to differentiate different tests).

Yes you are right, I think in general all the test result viewing pages can do with quite a bit of improvements. I am going to again take note of this and defer this improvements to future releases.

**Comment by lindanlee** [comment]
> We discussed this a bit with @ebdet2002 and came to the conclusion that the problem was that each sentence was placed inside of a new paragraph. Putting it all inside of the same paragraph makes it look a lot neater. We will go for this solution.

That sounds fine with me!

**Comment by lindanlee** [comment]
> I am going to take note of this as a possible future improvements, but am not going to implement this for the moment as it would require reworking how we manage deck specific documentation and possibly adding support for in-app contextual documentation (I don't like the idea of redirecting users to our website to consume crucial ooniprobe related documentation)

Got it. 

> Yes, though this keying is used also consistently across desktop and mobile clients. I think we are going for the moment keep it as is and defer potential improvements to the results page to future work.

Also reasonable. 

> Yes you are right, I think in general all the test result viewing pages can do with quite a bit of improvements. I am going to again take note of this and defer this improvements to future releases.

Again, I am fine with this, as long as this information isn't lost. Done is better than perfect!

**Comment by hellais** [comment]
I believe I have addressed all the addressable issues highlighted in your comments.

Please take a look at http://37.218.242.109:3000/ in case I missed something.

I did my best to improve responsiveness on mobile devices to the extent that it was possible to do so. That said mobile is not the main target platform so I think we should fix only things that are in the area of "ZOMG that is so broken" and not so much in the area of "it would look better if ...".

**Comment by lindanlee** [comment]
Thanks! I think you got all of the comments that we agreed upon to fix. Sweet! 

>I did my best to improve responsiveness on mobile devices to the extent that it was possible to do so. That said mobile is not the main target platform so I think we should fix only things that are in the area of "ZOMG that is so broken" and not so much in the area of "it would look better if ...".

I agree that this was the right course of action to do. But if we have some extra time in the future, we can throw some effort into this. It looks okayish for now and that's cool with me!

**Comment by hellais** [comment]
I am currently building a docker container with inside it the latest version of ooniprobe for you to try out.

**Comment by hellais** [comment]
@lindanlee @ebdet2002 A real ooniprobe with the new web UI lives here: http://37.218.242.109/client/#/

**Comment by elioqoshi** [comment]
Great cooperation everybody! I wanted to chime in earlier but it seems you handled it yourself pretty well! :)

**Comment by hellais** [comment]
Closing this as implemented.
