### ISSUE TITLE
Feedback from TorDev user risk session

### ISSUE THREAD

**Issue by agrabeli** [TheTorProject/ooni-wui#3]
Feedback from participants:
1. Consider re-phrasing the term "risks" to something like "detectability" (which is less scary)?
2. Instead of creating criteria for URL risk assessment, consider whitelisting and blacklisting URLs per country? Whitelists can include URLs that are commonly accessed and present almost no risk (e.g. Alexa top 100), while blacklists can include pornography, hate speech, and other objectionable categories.
3. State in the 1st paragraph of the risks documentation that to OONI's knowledge, none of the risks detailed in the documentation have actually happened...and that all of this is just speculative (in an attempt to inform users of what could potentially happen, though none of this has actually happened). 
4. Set-up wizard: Perhaps allow users to select options based on their threat models? Or make it clearer that the default options are actually the default (and why)? Provide "threat model questions" and based on those, provide suggestions to users?
5. Set-up wizard: Include a reset ("Get me out of here") button which allows users to exit the GUI if they do not consent to the risks.
6. Options to upload measurements: Briefly/concisely explain what each of the options are, or why they are recommended. For example, next to Tor hidden services, we can say "more private, but slower", or "recommended". 
7. Include simpler English in the documentation -- perhaps refer to Wikipedia Simple English?
8. Translations? It's important to ensure that users are able to read and understand the documentation in their local languages...
9. To ensure that new probe hosts understand the risks, configure the Raspberry Pi GUI so that it is de-activated after it has been used (and so that new probe hosts will have to consent when they use it).

**Comment by hellais** [comment]
Thanks for writing this down in here.

A lot of these are actually fairly big features. It would be good to actually split these up into more sizeable chunks of work that are achievable in a reasonable amount of time.

**Comment by agrabeli** [comment]
@hellais I've re-ordered the feedback to help point out what could/should be prioritised:

**1. Edit Risks documentation (agrabeli)** - October 2016
- Consider re-phrasing the term "risks" to something like "detectability" (which is less scary)?
- State in the 1st paragraph of the risks documentation that to OONI's knowledge, none of the risks detailed in the documentation have actually happened...and that all of this is just speculative (in an attempt to inform users of what could potentially happen, though none of this has actually happened).

**2. GUI Set-up Wizard**
- Include a reset ("Get me out of here") button which allows users to exit the GUI if they do not consent to the risks.
-  Briefly/concisely explain what each of the options are, or why they are recommended. For example, next to Tor hidden services, we can say "more private, but slower", or "recommended". 

**3. Raspberry Pi GUI**
- Configure the Raspberry Pi GUI so that it is de-activated after it has been used (and so that new probe hosts will have to consent when they use it). 

Low-hanging fruit (in the sense that the following points are open to further discussion and subject to funding, etc.):
- Instead of creating criteria for URL risk assessment, consider whitelisting and blacklisting URLs per country? Whitelists can include URLs that are commonly accessed and present almost no risk (e.g. Alexa top 100), while blacklists can include pornography, hate speech, and other objectionable categories.
- Set-up wizard: Perhaps allow users to select options based on their threat models? Or make it clearer that the default options are actually the default (and why)? Provide "threat model questions" and based on those, provide suggestions to users?
- Include simpler English in the documentation -- perhaps refer to Wikipedia Simple English?
- Translations? It's important to ensure that users are able to read and understand the documentation in their local languages...

I can plan to edit the Risks documentation this month, though not sure how many resources the changes to the desktop and Raspberry Pi GUI would need...

**Comment by agrabeli** [comment]
@hellais I've created new tickets for the various types of feedback above (which is why I'm closing this ticket).
