### ISSUE TITLE
mobile: missing encoding in results view

### ISSUE THREAD

**Issue by bassosimone** [TheTorProject/ooni-wui#44]
I have noticed, using ooniprobe-ios in italian, that the encoding is not correctly set, as showed by the following screenshot:

![screen shot 2017-03-16 at 17 57 04](https://cloud.githubusercontent.com/assets/337298/24008635/72e0c716-0a72-11e7-85fb-15f140c34a2b.png)

(and, yes, damn, I left the mouse pointer over the window and forgot that the emulator allows to take pictures much more efficiently than capturing all screen and cropping.)

**Comment by hellais** [comment]
I suspect this may have to do with how the pages are serve by ooniprobe-ios (and possibly also ooniprobe-android).

The meta tag is set properly and on desktop it works as expected:
![screen shot 2017-03-16 at 17 08 28 0000](https://cloud.githubusercontent.com/assets/424620/24008932/35942030-0a6b-11e7-9a77-e111f143369b.png)

**Comment by bassosimone** [comment]
Update: I see the problem *only* with iOS 8.4.

**Comment by bassosimone** [comment]
Issue moved to [TheTorProject/ooniprobe-ios #106](https://github.com/TheTorProject/ooniprobe-ios/issues/106) via [**ZenHub**](https://www.zenhub.com/)
