### ISSUE TITLE
Bandwidth units are mislabeled

### ISSUE THREAD

**Issue by hellais** [TheTorProject/ooni-wui#55]
It's reported in https://github.com/TheTorProject/ooniprobe-android/issues/116 that the bandwidth units are mis-represented in the results for NDT.

What should we use MBps (bytes per second) or Mbps (bits per second)?

**Comment by lorenzoPrimi** [comment]
I guess @bassosimone is the most indicated person to answer this

**Comment by bassosimone** [comment]
I would actually use: ${prefix}bit/s (megabit per second).
